#!/bin/sh

case "$1" in

  ""|start|restart|stop)
    exit 0
  ;;

  info)
    VER=`cat /etc/config/addons/www/script/VERSION`
    echo "Info: <b>Script-Parser CCU Addon</b><br>"
    echo "Info: <a href='https://github.com/jens-maus/scriptparser'>https://github.com/jens-maus/scriptparser</a>"
    echo "Name: Script-Parser"
    echo "Version: $VER"
    echo "Operations: uninstall"
    echo "Config-Url: /addons/script"
    echo "Update: /addons/script/update-check.cgi"
  ;;

  uninstall)
    rm -r /usr/local/etc/config/addons/www/script
  ;;

  *)
    echo "Usage: scriptparser {info|uninstall}" >&2
    exit 1
  ;; 

esac 

exit 0
